version: '3.8'

services:
  # Jenkins - основной CI/CD сервер

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt
    #command: jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
    networks:
      - cicd-network
    depends_on:
      - sonarqube
      
  ssh-agent:
    image: jenkins/ssh-agent
    networks:
      - cicd-network
    depends_on:
      - sonarqube
      
  # SonarQube - статический анализ кода
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - cicd-network
    depends_on:
      - postgres

  # PostgreSQL - база данных для SonarQube
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgresql_db:/var/lib/postgresql
    networks:
      - cicd-network

  # Nexus Repository - артефакты и зависимости
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - cicd-network

  # GitLab - система контроля версий
  #gitlab:
  #  image: gitlab/gitlab-ce:latest
  #  container_name: gitlab
  #  restart: unless-stopped
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #    - "22:22"
  #  environment:
  #    - GITLAB_OMNIBUS_CONFIG=|
  #        external_url 'http://localhost'
  #        gitlab_rails['gitlab_shell_ssh_port'] = 22
  #  volumes:
  #    - gitlab_config:/etc/gitlab
  #    - gitlab_logs:/var/log/gitlab
  #    - gitlab_data:/var/opt/gitlab
  #  networks:
  #    - cicd-network

  # Docker Registry - приватный реестр образов
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5002:5000"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
    volumes:
      - registry_data:/data
    networks:
      - cicd-network

  # Portainer - управление Docker
  #portainer:
  #  image: portainer/portainer-ce:latest
  #  container_name: portainer
  #  restart: unless-stopped
  #  ports:
  #    - "9001:9000"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - portainer_data:/data
  #  networks:
  #    - cicd-network
  jenkins_slave1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_slave1
    ports:
      - "3333:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd-network


  jenkins_slave2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_slave2
    ports:
      - "4444:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd-network


volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:
  postgresql_db:
  nexus_data:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  registry_data:
  portainer_data:

networks:
  cicd-network:
    driver: bridge